from browser_smoke import load, ROOT
from playwright.sync_api import sync_playwright
import json
checks=0
def check(value, message):
    global checks
    assert value, message
    checks+=1
with sync_playwright() as p:
    b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    page=b.new_page(viewport={'width':1280,'height':900})
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    load(page)
    # Offline injected audio interface records calls, no sound equipment required.
    page.evaluate('''()=>{window.audioLog=[];['on','off','sequence','sustain','metro','panic'].forEach(k=>PianoAudio[k]=(...args)=>audioLog.push({k,args}));}''')
    check(page.evaluate('NextPiano.version')=='2.0.0','version')
    for w,h in [(320,740),(390,844),(600,960),(800,1280),(1280,900),(1600,900),(900,430)]:
        page.set_viewport_size({'width':w,'height':h});page.wait_for_timeout(140)
        for view in ['studio','theory','ear','practice','metro','midi']:
            page.evaluate('(v)=>NextPiano.go(v)',view)
            check(page.evaluate('document.documentElement.scrollWidth<=innerWidth'),'overflow '+str(w)+view)
            check(page.locator('.pkey').count()>=13,'piano keys '+view)
            check(page.locator('main').bounding_box()['height']>0,'main visible')
    page.set_viewport_size({'width':1280,'height':900});page.wait_for_timeout(180)
    page.evaluate("NextPiano.go('studio')")
    page.locator('[data-studio="chord"]').click()
    page.locator('#root').select_option('C');page.locator('#chord').select_option('Major')
    check(page.locator('.pkey.selected').count()>=6,'chord highlights')
    page.locator('#inversion').select_option('1')
    page.locator('#listen').click()
    events=page.evaluate("audioLog.filter(x=>x.k==='sequence').at(-1).args[0]")
    check([e['note'] for e in events]==[52,55,60],'first inversion playback')
    page.keyboard.down('a');page.keyboard.down('d');page.keyboard.down('g')
    check(page.locator('#liveName').inner_text()=='C Major','QWERTY works with button focus')
    for k in ['a','d','g']:page.keyboard.up(k)
    check(page.locator('.pkey.pressed').count()==0,'QWERTY notes released')
    # Simulated native MIDI events, channel 2 and velocity-zero Note Off.
    page.evaluate("nativeEvent('midi',{status:145,a:60,b:85});nativeEvent('midi',{status:145,a:64,b:90});nativeEvent('midi',{status:145,a:67,b:100})")
    check(page.locator('#liveName').inner_text()=='C Major','MIDI chord recognizer')
    page.evaluate("nativeEvent('midi',{status:145,a:60,b:0});nativeEvent('midi',{status:129,a:64,b:0});nativeEvent('midi',{status:177,a:123,b:0})")
    check(page.locator('.pkey.pressed').count()==0,'MIDI cleanup')
    # Real CDP touch events exercise independent pointer capture and release.
    cdp=page.context.new_cdp_session(page)
    points=[]
    for i,n in enumerate([48,52]):
        box=page.locator('.pkey[data-note="%d"]'%n).bounding_box()
        points.append({'x':box['x']+box['width']/2,'y':box['y']+box['height']-20,'id':i+1})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':points})
    check(page.locator('.pkey.pressed').count()==2,'two concurrent touch notes')
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    check(page.locator('.pkey.pressed').count()==0,'multitouch releases')
    page.locator('[data-studio="scale"]').click()
    page.locator('#root').select_option('C');page.locator('#scale').select_option('Major (Ionian)')
    page.locator('#listen').click()
    seq=page.evaluate("audioLog.filter(x=>x.k==='sequence').at(-1).args[0]")
    check([x['note'] for x in seq]==[48,50,52,53,55,57,59,60],'chord inversion does not invert scale')
    page.evaluate("NextPiano.go('ear')")
    page.locator('#newEar').click()
    check(page.locator('.marker').count()==0,'ear answer hidden')
    check(page.locator('[data-ear-answer]').count()==5,'beginner answer pool')
    page.locator('[data-ear-answer="0"]').click()
    attempts=page.evaluate("NextPiano.getState().stats.ear.interval.attempts")
    check(attempts==1,'ear attempt counted')
    check(page.locator('[data-ear-answer]:disabled').count()==5,'answer counted only once')
    page.locator('#replayEar').click()
    check(page.evaluate("NextPiano.getState().stats.ear.interval.attempts")==1,'replay not counted')
    page.locator('#earType').select_option('repeat');page.locator('#newEar').click()
    note=page.evaluate("audioLog.filter(x=>x.k==='sequence').at(-1).args[0][0].note")
    page.evaluate('(n)=>nativeEvent("midi",{status:144,a:n,b:85})',note)
    check(page.evaluate("NextPiano.getState().stats.ear.repeat.correct")==1,'repeat pitch accepted via MIDI')
    page.evaluate('(n)=>nativeEvent("midi",{status:128,a:n,b:0})',note)
    page.evaluate("NextPiano.go('practice')")
    page.locator('#practiceType').select_option('chord');page.locator('#practiceRoot').select_option('C');page.locator('#practiceChord').select_option('Major')
    for n in [52,55,60]:page.evaluate('(n)=>nativeEvent("midi",{status:144,a:n,b:85})',n)
    check('Zaliczone' in page.locator('#taskTarget').inner_text(),'chord exercise inversion accepted')
    for n in [52,55,60]:page.evaluate('(n)=>nativeEvent("midi",{status:128,a:n,b:0})',n)
    page.locator('#practiceType').select_option('scale');page.locator('#practiceRoot').select_option('C');page.locator('#practiceScale').select_option('Major (Ionian)')
    for n in [48,50,52,53,55,57,59,60]:
        page.evaluate('(n)=>nativeEvent("midi",{status:144,a:n,b:85})',n)
        page.evaluate('(n)=>nativeEvent("midi",{status:128,a:n,b:0})',n)
    check('Zaliczone' in page.locator('#taskTarget').inner_text(),'scale sequence exercise')
    page.evaluate("NextPiano.go('theory')")
    page.locator('[data-lesson="enharmonic"]').click();page.locator('[data-quiz="1"]').click();page.locator('#lessonDone').click()
    check(page.evaluate("NextPiano.getState().stats.quiz.enharmonic.correct"),'lesson quiz')
    check('enharmonic' in page.evaluate("NextPiano.getState().stats.read"),'lesson marked')
    page.evaluate("NextPiano.go('metro')")
    page.locator('#meter').select_option('6/8');page.locator('#metroStart').click()
    cfg=page.evaluate("audioLog.filter(x=>x.k==='metro').at(-1).args[1]")
    check(cfg['beats']==2 and cfg['sub']==3,'6/8 dotted-quarter configuration')
    page.locator('#meter').select_option('7/8')
    cfg=page.evaluate("audioLog.filter(x=>x.k==='metro').at(-1).args[1]")
    check(cfg['beats']==7 and cfg['mask']==21,'7/8 accent mask')
    page.locator('#panic').click();check('Uruchom' in page.locator('#metroStart').inner_text(),'panic stops metro')
    page.evaluate("NextPiano.go('midi')")
    page.locator('#palette').select_option('mint');page.locator('#themeToggle').click()
    check(page.evaluate('document.documentElement.dataset.palette')=='mint','palette')
    check(page.evaluate('document.documentElement.dataset.theme')=='light','theme')
    page.wait_for_timeout(350)
    stored=page.evaluate('window.__store')
    restored=b.new_page(viewport={'width':390,'height':844});load(restored,stored)
    check(restored.evaluate('NextPiano.getState().stats.quiz.enharmonic.correct'),'progress restored from storage schema')
    check(restored.evaluate('NextPiano.getState().palette')=='mint','preferences restored')
    (ROOT/'test-results').mkdir(exist_ok=True)
    unexpected=errors
    check(not unexpected,'runtime errors '+repr(unexpected))
    report={'checks':checks,'result':'PASS','sizes':['320x740','390x844','600x960','800x1280','1280x900','1600x900','900x430'],'runtimeErrors':unexpected,'limitations':['Native MIDI events were simulated, no physical instrument.','Audio backend mocked for UI tests.','Storage simulated for about:blank; Android instrumentation tests real WebView separately.']}
    (ROOT/'test-results'/'ui-tests.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
    print(json.dumps(report,ensure_ascii=False,indent=2))
    b.close()
