plugins { id 'com.android.application' }
android {
    namespace 'com.mikczemny.nextpiano'
    compileSdk 36
    defaultConfig {
        applicationId 'com.mikczemny.nextpiano'
        minSdk 26
        targetSdk 36
        versionCode 20000
        versionName '2.0.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        debug { applicationIdSuffix '.preview'; versionNameSuffix '-preview' }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
